name: false_colour_index
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip:
      - audioread==3.0.1
      - librosa==0.10.2
      - matplotlib==3.9.0
      - numpy==1.26.0
      - psutil==6.0.0
      - resampy==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.14.0
      - six==1.16.0
      - soundfile==0.12.1
